<?php

namespace Plugin\AdminLoginAlert\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminLoginAlertConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminLoginAlertConfigRepository extends EntityRepository
{
}
