<?php

namespace DoctrineProxy\__CG__\Eccube\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Block extends \Eccube\Entity\Block implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'id', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'name', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'file_name', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'create_date', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'update_date', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'logic_flg', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'deletable_flg', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'BlockPositions', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'DeviceType');
        }

        return array('__isInitialized__', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'id', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'name', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'file_name', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'create_date', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'update_date', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'logic_flg', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'deletable_flg', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'BlockPositions', '' . "\0" . 'Eccube\\Entity\\Block' . "\0" . 'DeviceType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Block $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileName($fileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileName', array($fileName));

        return parent::setFileName($fileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileName', array());

        return parent::getFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', array($createDate));

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', array());

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', array($updateDate));

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', array());

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogicFlg($logic_flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogicFlg', array($logic_flg));

        return parent::setLogicFlg($logic_flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogicFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogicFlg', array());

        return parent::getLogicFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletableFlg($deletableFlg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletableFlg', array($deletableFlg));

        return parent::setDeletableFlg($deletableFlg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletableFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletableFlg', array());

        return parent::getDeletableFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function addBlockPosition(\Eccube\Entity\BlockPosition $blockPositions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBlockPosition', array($blockPositions));

        return parent::addBlockPosition($blockPositions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBlockPosition(\Eccube\Entity\BlockPosition $blockPositions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBlockPosition', array($blockPositions));

        return parent::removeBlockPosition($blockPositions);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockPositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockPositions', array());

        return parent::getBlockPositions();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceType(\Eccube\Entity\Master\DeviceType $deviceType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceType', array($deviceType));

        return parent::setDeviceType($deviceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceType', array());

        return parent::getDeviceType();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', array($offset));

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', array($offset, $value));

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', array($offset));

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', array($offset));

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', array($arrProps, $excludeAttribute, $parentClass));

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($excludeAttribute, $parentClass));

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', array($srcObject, $excludeAttribute));

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

}
