<?php

namespace Plugin\SimpleSiteMaintenance\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SimpleSiteMaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleSiteMaintenanceRepository extends EntityRepository
{

    public $app;

    public function setApplication($app) {
        $this->app = $app;
    }

    public function get()
    {
        $arrResult = $this->findAll();

        /* @var $result \Plugin\SimpleSiteMaintenance\Entity\SsmConfig */
        $SsmConfig = array();
        foreach ($arrResult as $result) {
            $SsmConfig = $result;
            break;
        }

        return $SsmConfig;
    }
}
